name: CI
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/$default_branch' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $default_branch"
