name: CI
on: push
jobs:
  prod-check:
    if: ${{ always() && format('refs/heads/{0}', ) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch "
