name: CI
on: push
jobs:
  prod-check:
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch ${{ github.event.repository.default_branch }}"
